language: go

script:
    - go test -v ./...

install:
    - cd $GOPATH/src/github.com/kotoko/chihaya/
    - cp config.json.example config.json
    - go get -v
    - go build -v
    - mysql < mysql_test_schema.sql
