language: go

script:
    - go test -v ./...

before_script:
    - cp config.json.example config.json
    - cp -rfv ./* $GOPATH/src/github.com/kotoko/chihaya/
    - go build -v github.com/kotoko/chihaya
    - go install -v github.com/kotoko/chihaya
    - ./mySQL_sample_setup.sh 
